# ============================================================
# CLOUDWATCH ALARMS (untuk monitoring Lambda error)
# ============================================================

PredictionErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: PredictionError
    AlarmDescription: "Alarm aktif jika Lambda Prediction memiliki error > 0 dalam 1 menit"
    Namespace: AWS/Lambda
    MetricName: Errors
    Dimensions:
      - Name: FunctionName
        Value: Prediction
    Statistic: Sum
    Period: 60
    EvaluationPeriods: 1
    Threshold: 0
    ComparisonOperator: GreaterThanThreshold
    TreatMissingData: notBreaching
    AlarmActions:
      - !Ref NotificationMail   # butuh SNS topic dengan nama ini
    OKActions:
      - !Ref NotificationMail

ForecastingErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: ForecastingError
    AlarmDescription: "Alarm aktif jika Lambda Forecasting memiliki error > 0 dalam 1 menit"
    Namespace: AWS/Lambda
    MetricName: Errors
    Dimensions:
      - Name: FunctionName
        Value: Forecasting
    Statistic: Sum
    Period: 60
    EvaluationPeriods: 1
    Threshold: 0
    ComparisonOperator: GreaterThanThreshold
    TreatMissingData: notBreaching
    AlarmActions:
      - !Ref NotificationEmail
    OKActions:
      - !Ref NotificationEmail